set -g default-terminal "screen-256color"
set -g base-index 0
setw -g pane-base-index 0
set -g default-shell "/Users/asyl/.nix-profile/bin/zsh"

set -g status-keys vi
set -g mode-keys vi

unbind C-b
set -g prefix C-,
bind -N "Send the prefix key through to the application" C-, send-prefix

set -g mouse on
set -g focus-events on
setw -g aggressive-resize off
setw -g clock-mode-style 24
set -s escape-time 0
set -g history-limit 50000

set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'

set -g @continuum-restore 'on'
set -g @continuum-boot 'off'
set -g @continuum-save-interval '10'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

bind-key -n C-h if -F "#{@pane-is-vim}" 'send-keys C-h' 'select-pane -L'
bind-key -n C-j if -F "#{@pane-is-vim}" 'send-keys C-j' 'select-pane -D'
bind-key -n C-k if -F "#{@pane-is-vim}" 'send-keys C-k' 'select-pane -U'

bind-key -n M-h if -F "#{@pane-is-vim}" 'send-keys M-h' 'resize-pane -L 3'
bind-key -n M-j if -F "#{@pane-is-vim}" 'send-keys M-j' 'resize-pane -D 3'
bind-key -n M-k if -F "#{@pane-is-vim}" 'send-keys M-k' 'resize-pane -U 3'
bind-key -n M-l if -F "#{@pane-is-vim}" 'send-keys M-l' 'resize-pane -R 3'

bind-key -n 'C-\' if -F "#{@pane-is-vim}" 'send-keys C-\\' 'select-pane -l'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

set -g allow-passthrough on

set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set -g default-command '$SHELL'

set -g status-right " "

set -g pane-border-style 'fg=yellow'
set -g pane-active-border-style 'fg=yellow'

setw -g clock-mode-colour yellow
setw -g mode-style 'fg=black bg=yellow bold'

set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=yellow'

set -g status-left ' #{?client_prefix,[,}#{session_name}#{?client_prefix,],} '
set -g status-left-length 20

setw -g window-status-current-style 'underscore'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=yellow bg=black'
setw -g window-status-separator ""
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '

setw -g window-status-bell-style 'fg=yellow bg=yellow bold'

set -g message-style 'fg=yellow bg=black bold'

set -g set-titles on
set -g set-titles-string '#T - #S / #W'

run '$HOMEBREW_PREFIX/opt/tpm/share/tpm/tpm'
